### ISSUE TITLE
Registration code is incorrect. Exception while invoking method 'entryValidateSignupCode'

### ISSUE THREAD

**Issue by BarinsGhost** [Differential/accounts-entry#391]
Hey, I am new to github, apologies if this is not the right place for this. I've searched google for 2 hours now and nothing seems to fix this issue.

Basically, I installed the joshowens:accounts-entry using:
`meteor add joshowens:accounts-entry`
After getting and error regarding incompatibility, I found a solution that fixed that.
Creating a packages folder in the project root and cloning github repo in there fixed the issue. Sign-in, sign-up and others render pages. There were the steps:
```
mkdir packages
cd packages
git clone https://github.com/Differential/accounts-entry.git
```
However, whenever I try to register as a new user, I get the "Registration code is incorrect." error. 
Here is the server log: 
```
I20160221-20:00:20.756(10)? Exception while invoking method 'entryValidateSignupCode' ReferenceError: Match is not defined
I20160221-20:00:20.757(10)?     at [object Object].Meteor.methods.entryValidateSignupCode (packages/joshowens_accounts-entry/server/e
ntry.coffee:18:25)
I20160221-20:00:20.757(10)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160221-20:00:20.758(10)?     at livedata_server.js:708:19
I20160221-20:00:20.758(10)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160221-20:00:20.758(10)?     at livedata_server.js:706:40
I20160221-20:00:20.758(10)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160221-20:00:20.758(10)?     at livedata_server.js:704:46
I20160221-20:00:20.758(10)?     at tryCallTwo (/Users/b/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_m
odules/meteor-promise/node_modules/promise/lib/core.js:45:5)
I20160221-20:00:20.758(10)?     at doResolve (/Users/b/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_mo
dules/meteor-promise/node_modules/promise/lib/core.js:171:13)
I20160221-20:00:20.759(10)?     at new Promise (/Users/b/.meteor/packages/promise/.0.5.1.8idxpg++os+web.browser+web.cordova/npm/node_
modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
```
Here is the client log: 
`errorClass {error: 500, reason: "Internal server error", details: undefined, message: "Internal server error [500]", errorType: "Meteor.Error"}`

How do I fix this?

**Comment by selaias** [comment]
meteor add check

**Comment by BarinsGhost** [comment]
Awesome! Thank you very much @selaias !!!
